Add validations
mancho-devs/npm-modules pull request #1
Opened 2021-05-12 09:31 UTC by mambetakunova

2021-05-12 09:39 UTC, kadishmal requested changes

2021-05-12 09:39 UTC, kadishmal commented on validations/index.ts
> +    if (!userId) {
Indentation is wrong.

2021-05-12 09:39 UTC, kadishmal commented on validations/test/index.test.ts
> +  it('should throw exception if prop is below zero', async () => {
`if prop` => `if value`

2021-05-12 09:39 UTC, kadishmal commented on validations/test/index.test.ts
> +  it('should throw exception if prop is not number', async () => {
Here as well.

2021-05-12 09:39 UTC, kadishmal commented on validations/.gitignore
> +*.js
The repository structure should be similar to that of [`react-components`](https://github.com/mancho-devs/react-components) repository.

2021-05-13 10:29 UTC, mambetakunova commented on validations/index.ts
> +    if (!userId) {
done

2021-05-13 10:30 UTC, mambetakunova commented on validations/test/index.test.ts
> +  it('should throw exception if prop is below zero', async () => {
done

2021-05-13 10:30 UTC, mambetakunova commented on validations/test/index.test.ts
> +  it('should throw exception if prop is not number', async () => {
done

2021-05-13 10:30 UTC, mambetakunova commented on validations/.gitignore
> +*.js
done

2021-05-14 05:58 UTC, kadishmal approved these changes
Сонун! 👍

2021-05-14 05:59 UTC, merged